version: "3"
services:
  splatoon3_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: splatoon3_bot
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./splatoon3_bot/plugins/splatoon3_bot/resource/data.sqlite:/app/splatoon3_bot/plugins/splatoon3_bot/resource/data.sqlite
    ports:
      - 8080:8080
